DEFAULT:
  DISCORD_WEBHOOK_URL: "url"
  EDGE_DRIVER_LOCATION: "/usr/local/bin/msedgedriver"
  USERNAME: "cpf"
  PASSWORD: "senha"
  PUBLICO_GERAL: False
  UNIDADES_SELECIONADAS:
    - "Av. Paulista"
    - "Vila Mariana"
    - "Cpf"
    - "Consolação"
    - "Mogi Das Cruzes"
  URL_LOGIN: "https://centralrelacionamento.sescsp.org.br"
  NOME_CURSO: "Esporte jovem"
  CATEGORIA_CURSO: "Esporte e Atividade física"

UNIDADES:
  "14 Bis": "Sesc 14 Bis"
  "24 de Maio": "Sesc 24 de Maio"
  "Av. Paulista": "Sesc Avenida Paulista"
  "Belenzinho": "Sesc Belenzinho"
  "Bom Retiro": "Sesc Bom Retiro"
  "Campo Limpo": "Sesc Campo Limpo"
  "Carmo": "Sesc Carmo"
  "Casa Verde": "Sesc Casa Verde"
  "Cinesesc": "Sesc Cinesesc"
  "Consolação": "Sesc Consolação"
  "Cpf": "Centro de Pesquisa E Formação"
  "Dom Pedro": "Sesc Dom Pedro"
  "Florêncio": "Sesc Florêncio"
  "Guarulhos": "Sesc Guarulhos"
  "Interlagos": "Sesc Interlagos"
  "Ipiranga": "Sesc Ipiranga"
  "Itaquera": "Sesc Itaquera"
  "Mogi Das Cruzes": "Sesc Mogi Das Cruzes"
  "Osasco": "Sesc Osasco"
  "Pinheiros": "Sesc Pinheiros"
  "Pompeia": "Sesc Pompeia"
  "Santana": "Sesc Santana"
  "Santo Amaro": "Sesc Santo Amaro"
  "Santo André": "Sesc Santo André"
  "São Caetano": "Sesc São Caetano"
  "Vila Mariana": "Sesc Vila Mariana"
